package com.pi.remote.securenet

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.ByteArrayInputStream
import java.security.cert.CertificateFactory
import java.security.cert.X509Certificate
import java.util.Base64

/**
 * PinCodec — JVM unit tests for the hex → OkHttp Base64 conversion boundary.
 *
 * These tests mirror `apps/mobile/tests/pin-codec.test.ts` on the TS side,
 * ensuring both layers agree on the same SPKI digest → pin format.
 *
 * The test vectors cover:
 *  - Known SHA-256 SPKI digests (hex → Base64 round-trip)
 *  - Fail-closed behavior: empty, wrong-length, non-hex pins throw PinCodecError
 *  - The `sha256/<base64>` format OkHttp expects (not `sha256/<hex>=`)
 */
class PinCodecTest {

    // ------------------------------------------------------------------
    // Known test vectors — hex → Base64 → OkHttp pin format
    // ------------------------------------------------------------------

    /** All-zeros pin (32 zero bytes). Base64 of 32 zero bytes is 43 'A's + '='. */
    private val ZERO_HEX = "0".repeat(64)
    private val ZERO_BASE64 = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
    private val ZERO_OKHTTP_PIN = "sha256/$ZERO_BASE64"

    /**
     * A real-world SPKI SHA-256 digest (from a common test certificate).
     * This is the hex of the SHA-256 of the SubjectPublicKeyInfo of a
     * well-known test cert. The Base64 is the standard encoding.
     */
    private val SAMPLE_HEX = "5dbe1690e9b7e1c6c8c8c8c8c8c8c8c8c8c8c8c8c8c8c8c8c8c8c8c8c8c8c8c8"
    private val SAMPLE_BASE64 = "Xb4WkOm34cbIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMg="
    private val SAMPLE_OKHTTP_PIN = "sha256/$SAMPLE_BASE64"

    /**
     * Public DER certificate fixture generated by the Rust rcgen identity path.
     * Its private key is intentionally not stored; this locks the real
     * certificate-SPKI -> QR hex -> Android trust-manager boundary.
     */
    private val RUST_CERT_DER_BASE64 =
        "MIIBXjCCAQSgAwIBAgIUFOv7YxcEJMQEyLQQ+yJPyK5fq0QwCgYIKoZIzj0EAwIwITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDAgFw03NTAxMDEwMDAwMDBaGA80MDk2MDEwMTAwMDAwMFowITEfMB0GA1UEAwwWcmNnZW4gc2VsZiBzaWduZWQgY2VydDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABATv2tQGdGTzQfrk3Sf15iuYfaMAyCtoE0Zu7Xr+fqxlFs7Fmtq1scf7FaWqhlYdHOyPlGFpCOfflJrAbjpCSISjGDAWMBQGA1UdEQQNMAuCCWxvY2FsaG9zdDAKBggqhkjOPQQDAgNIADBFAiBkJRwTuwNmruBobWcaUR9TGSWfsfWfoGudYwtBU8Jl6gIhANN8pkuY+NUZNmYMS7jHMgxzuwxdemClgKqqgAbQXSuE"
    private val RUST_CERT_PIN_HEX =
        "c8c833670f4245dd6670ad9b910ee9613852671b0e5209c1facb22ba4e08b692"
    private val ATTACKER_CERT_DER_BASE64 =
        "MIICujCCAaKgAwIBAgIIT5uf/uWVy04wDQYJKoZIhvcNAQELBQAwHTEbMBkGA1UEAxMSYXR0YWNrZXItdGVzdC1vbmx5MB4XDTI2MDgwOTE1NTk0MFoXDTI3MDgxMDE1NTk0MFowHTEbMBkGA1UEAxMSYXR0YWNrZXItdGVzdC1vbmx5MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3GRNKXy6UYsg7k+ueYjDH8aWz3EyKoiU3xVzez+6L2xC23kbkK/EZJM/Gi3lYFyO5i55h4u58FgkcJ6OeHN8d5yW4ZIV4QYpodiqBlhKRFfUPxBXUT9hUfadtxq7ZI7Z0nT5HSkXswof74tCNph6NACYjRsb3lc+OWbIb7fkk5UgrimUpr0PJJnX1qKUMvmGUi6Eofru2kVUMSyqtef7s3zSHRABWopQzhiUIJ895ZsOaryU4kiStDDvXwJvyrSrSfA3tQAxJzGVfcyeXsz32CY0XXHNNdIReWPRFq8MYmEhX0QegrV55R7zepA9xIQrQ2KjnfleiqaE2XIImoOsuQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQAQDfwLOpOre3mRnmmTU2XKY2MjKAMYKpNO55rTyxjHqBf9oTHy3wXcuR+4KryqaqzEJcPz1J5wvq9EBB9y6fd82Tt2t1BJh0oHVQVAekVR1Rvn8bYQW0U8Yv2NyEvFdnJdk/YtV7lsKFAWyEiD3TLVhGoCMHqQ9f416i7nEVCffCJe4AkBjGPIHmGIByow2x5VmodUZm/y3G9wymoVkxzz4gkO8m6Sabi2PQEcZnbVt9sn+lz0N+oXVynvUiq7uTVMBH1WgU4asCCS451uD6TNkHSLJDt+s2QKKPChYApBJPrypMM8J9GTRQp9/E9VqBUsHlV2/tCTB2DgYhhtZ7Xu"

    // ------------------------------------------------------------------
    // formatOkHttpPin — the core conversion
    // ------------------------------------------------------------------

    @Test
    fun `formatOkHttpPin converts all-zeros hex to correct sha256-slash-base64`() {
        val pin = PinCodec.formatOkHttpPin(ZERO_HEX)
        assertEquals(ZERO_OKHTTP_PIN, pin)
        assertTrue(pin.startsWith("sha256/"))
    }

    @Test
    fun `formatOkHttpPin converts sample hex to correct base64`() {
        val pin = PinCodec.formatOkHttpPin(SAMPLE_HEX)
        assertEquals(SAMPLE_OKHTTP_PIN, pin)
    }

    @Test
    fun `Rust certificate fixture is accepted by the SPKI trust manager`() {
        val certificate = rustCertificateFixture()
        val manager = SpkiPinTrustManager(PinCodec.hexToBytes(RUST_CERT_PIN_HEX))

        manager.checkServerTrusted(arrayOf(certificate), "ECDHE_ECDSA")
    }

    @Test(expected = PinMismatchException::class)
    fun `SPKI trust manager rejects a different QR pin`() {
        val certificate = rustCertificateFixture()
        val manager = SpkiPinTrustManager(ByteArray(32))

        manager.checkServerTrusted(arrayOf(certificate), "ECDHE_ECDSA")
    }

    @Test(expected = PinMismatchException::class)
    fun `SPKI trust manager rejects attacker leaf even when pinned cert is appended`() {
        val pinnedCertificate = rustCertificateFixture()
        val attackerCertificate = certificateFixture(ATTACKER_CERT_DER_BASE64)
        val manager = SpkiPinTrustManager(PinCodec.hexToBytes(RUST_CERT_PIN_HEX))

        manager.checkServerTrusted(
            arrayOf(attackerCertificate, pinnedCertificate),
            "ECDHE_RSA",
        )
    }

    @Test
    fun `nested TLS pin failure keeps actionable expected and peer pins`() {
        val certificate = rustCertificateFixture()
        val manager = SpkiPinTrustManager(ByteArray(32))
        val mismatch = try {
            manager.checkServerTrusted(arrayOf(certificate), "ECDHE_ECDSA")
            error("should have rejected mismatched pin")
        } catch (e: PinMismatchException) {
            e
        }
        val wrapped = javax.net.ssl.SSLHandshakeException("handshake failed").apply {
            initCause(mismatch)
        }

        val detail = pinMismatchDetail(wrapped)
        assertTrue(detail?.contains("expected sha256/") == true)
        assertTrue(detail?.contains("peer sha256/") == true)
    }

    @Test
    fun `endpoint pin keys are scoped by host and port and accept WSS`() {
        assertEquals(
            EndpointKey("192.168.31.199", 8443),
            EndpointKey.fromUrl("https://192.168.31.199:8443/health"),
        )
        assertEquals(
            EndpointKey("192.168.31.199", 8443),
            EndpointKey.fromUrl("wss://192.168.31.199:8443/v1/events"),
        )
        assertNotEquals(
            EndpointKey.fromParts("192.168.31.199", 8443),
            EndpointKey.fromParts("192.168.31.199", 9443),
        )
    }

    @Test
    fun `endpoint pin keys reject cleartext and invalid ports`() {
        assertEquals(null, EndpointKey.fromUrl("http://192.168.31.199:8443/health"))
        assertEquals(null, EndpointKey.fromUrl("ws://192.168.31.199:8443/v1/events"))
        assertEquals(null, EndpointKey.fromParts("192.168.31.199", 0))
    }

    @Test
    fun `formatOkHttpPin never uses the naive sha256-slash-hex hack`() {
        // The old broken approach was "sha256/<hex>=" which never matches a
        // real certificate. The correct output is "sha256/<base64>".
        val pin = PinCodec.formatOkHttpPin(ZERO_HEX)
        assertNotEquals("sha256/$ZERO_HEX=", pin)
        assertNotEquals("sha256/$ZERO_HEX", pin)
    }

    // ------------------------------------------------------------------
    // hexToBytes — decoding
    // ------------------------------------------------------------------

    @Test
    fun `hexToBytes decodes 64-char hex to 32 bytes`() {
        val bytes = PinCodec.hexToBytes(ZERO_HEX)
        assertEquals(32, bytes.size)
        bytes.forEach { assertEquals(0.toByte(), it) }
    }

    @Test
    fun `hexToBytes decodes sample hex correctly`() {
        val bytes = PinCodec.hexToBytes(SAMPLE_HEX)
        assertEquals(32, bytes.size)
        // First byte: 0x5d = 93
        assertEquals(0x5d.toByte(), bytes[0])
        // Second byte: 0xbe = 190
        assertEquals(0xbe.toByte(), bytes[1])
    }

    // ------------------------------------------------------------------
    // Fail-closed validation
    // ------------------------------------------------------------------

    @Test(expected = PinCodecError::class)
    fun `rejects empty pin`() {
        PinCodec.hexToBytes("")
    }

    @Test
    fun `empty pin has 'empty' error code`() {
        try {
            PinCodec.hexToBytes("")
            error("should have thrown")
        } catch (e: PinCodecError) {
            assertEquals("empty", e.code)
        }
    }

    @Test(expected = PinCodecError::class)
    fun `rejects wrong-length pin`() {
        PinCodec.hexToBytes("abc123") // 6 chars, not 64
    }

    @Test
    fun `wrong-length pin has 'invalid_length' error code`() {
        try {
            PinCodec.hexToBytes("abc123")
            error("should have thrown")
        } catch (e: PinCodecError) {
            assertEquals("invalid_length", e.code)
        }
    }

    @Test(expected = PinCodecError::class)
    fun `rejects non-hex characters`() {
        val badHex = "g".repeat(64) // 'g' is not a hex char
        PinCodec.hexToBytes(badHex)
    }

    @Test
    fun `non-hex pin has 'invalid_chars' error code`() {
        try {
            PinCodec.hexToBytes("g".repeat(64))
            error("should have thrown")
        } catch (e: PinCodecError) {
            assertEquals("invalid_chars", e.code)
        }
    }

    // ------------------------------------------------------------------
    // isValidHexPin
    // ------------------------------------------------------------------

    @Test
    fun `isValidHexPin returns true for valid 64-char hex`() {
        assertTrue(PinCodec.isValidHexPin(ZERO_HEX))
        assertTrue(PinCodec.isValidHexPin(SAMPLE_HEX))
    }

    @Test
    fun `isValidHexPin returns false for invalid pins without throwing`() {
        assertFalse(PinCodec.isValidHexPin(""))
        assertFalse(PinCodec.isValidHexPin("abc"))
        assertFalse(PinCodec.isValidHexPin("g".repeat(64)))
    }

    // ------------------------------------------------------------------
    // Case insensitivity
    // ------------------------------------------------------------------

    @Test
    fun `accepts uppercase hex (case-insensitive)`() {
        val upperHex = "A".repeat(64)
        val lowerHex = "a".repeat(64)
        val upperPin = PinCodec.formatOkHttpPin(upperHex)
        val lowerPin = PinCodec.formatOkHttpPin(lowerHex)
        // Both should produce the same Base64 (0xAA... = same bytes)
        assertEquals(upperPin, lowerPin)
    }

    @Test
    fun `mixed-case hex decodes correctly`() {
        val mixedHex = "AbCdEf".repeat(10) + "AbCd" // 64 chars
        val bytes = PinCodec.hexToBytes(mixedHex)
        assertEquals(32, bytes.size)
        // First byte: 0xAB = 171
        assertEquals(0xAB.toByte(), bytes[0])
    }

    private fun rustCertificateFixture(): X509Certificate {
        return certificateFixture(RUST_CERT_DER_BASE64)
    }

    private fun certificateFixture(derBase64: String): X509Certificate {
        val der = Base64.getDecoder().decode(derBase64)
        return CertificateFactory.getInstance("X.509")
            .generateCertificate(ByteArrayInputStream(der)) as X509Certificate
    }
}
